version: "3"
services:
  client:
    image: "germinglin/multi-client-10-15"
    mem_limit: 128m
    hostname: client
  server:
    image: "germinglin/multi-server-10-15"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "germinglin/multi-worker-10-15"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "germinglin/multi-nginx-10-15"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"